### ISSUE TITLE
Files not available

### ISSUE THREAD

**Issue by S4NdeeP** [LisaAnne/Hallucination#1]
Hello Lisa,

We ran the script setup.sh. However, the files hosted at https://people.eecs.berkeley.edu/~lisa_anne/hallucination/ are no longer available. Please advice.

Regards,
Sandeep

**Comment by LisaAnne** [comment]
Can you see the zip files here? https://drive.google.com/drive/u/1/folders/1dnci1Kv6ez-hsFOqZt_gwiAv2FTAjDP4

**Comment by S4NdeeP** [comment]
Yes. Thanks.
