### ISSUE TITLE
Files not available...

### ISSUE THREAD

**Issue by XixiLiu95** [LisaAnne/Hallucination#2]
Hej Lisa,

Nice work and clean codes!  It seems that the files 
" 
wget https://people.eecs.berkeley.edu/~lisa_anne/hallucination/gt_labels.p
wget https://people.eecs.berkeley.edu/~lisa_anne/hallucination/vocab.p
wget https://people.eecs.berkeley.edu/~lisa_anne/hallucination/human_scores.zip" 

are not available anymore.  It would be nice for me to have it in order to have a better understanding about the image consistency and language consistency in your paper.  

Thanks a lot!

**Comment by arohrbach** [comment]
Please see here: https://drive.google.com/drive/u/1/folders/1dnci1Kv6ez-hsFOqZt_gwiAv2FTAjDP4

**Comment by XixiLiu95** [comment]
Thanks for the prompt response!
